#!/bin/bash

header() {

    echo ""
    echo "-----------------------------------------------------------"
    echo $*
    echo "-----------------------------------------------------------"
    echo ""
}

KERNELVERSION=`uname -r`

header "Preparation: install linux packages. Say yes to all updates."
sudo apt-get install fakeroot build-essential crash kexec-tools makedumpfile kernel-wedge
sudo apt-get build-dep linux
sudo apt-get install git-core libncurses5 libncurses5-dev libelf-dev binutils-dev

header "Preparation: install Autotools packages. Say yes to all updates."
sudo apt-get install libtool autoconf

header "Preparation: install Infiniband packages. Say yes to all updates."
sudo apt-get install libibverbs1 libibcm1 libibcm-dev  libibverbs-dev  libibcommon1 ibverbs-utils
sudo apt-get install rdmacm-utils librdmacm1 librdmacm-dev

header "Create file /etc/udev/rules.d/40-ib.rules"
echo "####  /etc/udev/rules.d/40-ib.rules  ####
KERNEL==\"umad*\", NAME=\"infiniband/%k\"
KERNEL==\"issm*\", NAME=\"infiniband/%k\"
KERNEL==\"ucm*\", NAME=\"infiniband/%k\", MODE=\"0666\"
KERNEL==\"uverbs*\", NAME=\"infiniband/%k\", MODE=\"0666\"
KERNEL==\"uat\", NAME=\"infiniband/%k\", MODE=\"0666\"
KERNEL==\"ucma\", NAME=\"infiniband/%k\", MODE=\"0666\"
KERNEL==\"rdma_cm\", NAME=\"infiniband/%k\", MODE=\"0666\"
########" > 40-ib.rules
sudo mv 40-ib.rules /etc/udev/rules.d/40-ib.rules


header "Start Infiniband kernel modules"
sudo modprobe rdma_cm
sudo modprobe ib_uverbs
sudo modprobe rdma_ucm
sudo lsmod
ls /dev/infiniband


header "Download Soft-iWarp software"
cd ~
mkdir -p Software
cd Software
mkdir -p softiwarp
cd softiwarp
if [ ! -d kernel ]; then
    git clone http://git.gitorious.org/softiwarp/kernel.git
fi
if [ ! -d userlib ]; then
    git clone http://git.gitorious.org/softiwarp/userlib.git
fi


header "Build Soft-iWarp kernel code"
cd kernel/softiwarp
make
sudo make install
cd ../..


header "Build Soft-iWarp userlib code"
cd userlib/libsiw-0.1
./autogen.sh
./autogen.sh
./configure
make
sudo make install
cd ../..



header "Start Soft-iWarp kernel module"
sudo modprobe  rdma_cm
sudo modprobe ib_uverbs
sudo insmod  /lib/modules/${KERNELVERSION}/extra/siw.ko
sudo ldconfig
sudo lsmod
ls /dev/infiniband/

header "Infiniband devices"
ibv_devices

header "Infiniband devinfo"
ibv_devinfo



